# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'pndong-github-io'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: Featured Projects
    submenu:
      - name: Coming soon
        link: /projects/Coming soon
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/pndong
    
